_format_version: "3.0"
plugins:
  - name: opentelemetry
    config:
      endpoint: "http://jaeger-collector:4318/v1/traces"
      resource_attributes: 
        service.name: "kong.dev"
  - name: prometheus
    config:
      bandwidth_metrics: true
      latency_metrics: true
      per_consumer: false
      status_code_metrics: true
      upstream_health_metrics: true

services:
  - name: httpbin-service
    enabled: true
    host: httpbin
    path: /
    port: 80
    protocol: http
    retries: 0
    tags:
      - httpbin
    connect_timeout: 60000
    read_timeout: 60000
    write_timeout: 60000
    routes:
      - name: httpbin-route
        protocols:
          - http
          - https
        paths:
          - /bin
        strip_path: true
        path_handling: v0
        preserve_host: false
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        https_redirect_status_code: 426